<template>
  <div class="flex items-center justify-center min-h-[60vh] px-6 py-16 sm:py-24 text-center">
    <div class="max-w-3xl mx-auto">
      <!-- Viking Bear Image -->
      <div class="flex flex-col items-center mb-12">
        <picture class="block w-full max-w-xs sm:max-w-sm">
          <source srcset="/images/404_viking_bear.webp" type="image/webp" />
          <img
            src="/images/404_viking_bear.png"
            alt="A Viking and a bear sitting together by a campfire at night, having fallen asleep while building the page - symbolizing collaboration across differences"
            class="w-full h-auto"
          />
        </picture>
        <p class="text-xs text-[var(--vp-c-text-3)] mt-2 italic">
          Image generated by Gemini using Imagen
        </p>
      </div>

      <!-- Title -->
      <h1 class="!text-3xl sm:!text-2xl font-bold leading-tight mb-4 mt-6 text-[var(--vp-c-text-1)]">
        We were building this page, but...
      </h1>

      <!-- Description -->
      <p class="text-lg sm:text-base leading-relaxed text-[var(--vp-c-text-2)] mb-12 max-w-2xl mx-auto">
        ...we fell asleep by the campfire.
      </p>

      <!-- Action Buttons -->
      <div class="flex flex-col sm:flex-row gap-4 justify-center mb-8 mt-8">
        <a
          href="/"
          class="inline-block px-6 py-3 rounded-md font-semibold no-underline transition-all duration-250 bg-[var(--vp-c-brand)] !text-white hover:bg-[var(--vp-c-brand-dark)]"
        >
          Take Me Home
        </a>
        <a
          href="/blog/"
          class="inline-block px-6 py-3 rounded-md font-semibold no-underline transition-all duration-250 bg-[var(--vp-c-bg-soft)] text-[var(--vp-c-text-1)] border border-[var(--vp-c-divider)] hover:border-[var(--vp-c-brand)] hover:text-[var(--vp-c-brand)]"
        >
          Read the Blog
        </a>
        <a
          href="/contact"
          class="inline-block px-6 py-3 rounded-md font-semibold no-underline transition-all duration-250 bg-[var(--vp-c-bg-soft)] text-[var(--vp-c-text-1)] border border-[var(--vp-c-divider)] hover:border-[var(--vp-c-brand)] hover:text-[var(--vp-c-brand)]"
        >
          Contact Us
        </a>
      </div>

      <!-- Quote -->
      <p class="text-sm italic text-[var(--vp-c-text-3)] mt-8">
        Building together takes dedication... and sometimes a good nap.
      </p>
    </div>
  </div>
</template>

<script setup lang="ts">
// Custom 404 page component
</script>
