<script setup lang="ts">
import { ref, onMounted } from 'vue'

interface ParsedSection {
  title: string
  description: string
}

interface ParsedPost {
  title: string
  series: string
  estimated: string
  tags: string[]
  summary: string
  sections: ParsedSection[]
  takeaways: string[]
}

type PageState =
  | 'loading'
  | 'error-invalid'
  | 'error-notfound'
  | 'error-wrong-label'
  | 'redirecting'
  | 'published'
  | 'preview'

const state = ref<PageState>('loading')
const post = ref<ParsedPost | null>(null)

// Top-level field labels generated by the GitHub Forms issue template
const TOP_LEVEL_FIELDS = [
  'post title',
  'series (optional)',
  'estimated publish',
  'tags',
  'summary',
  'sections',
  'key takeaways',
]

function isTopLevelField(line: string): boolean {
  const normalized = line.trim().toLowerCase()
  return TOP_LEVEL_FIELDS.some(f => normalized === `### ${f}`)
}

// Returns the first non-empty line after the matching ### heading
function parseField(body: string, label: string): string {
  const lines = body.split('\n')
  const target = `### ${label.toLowerCase()}`
  const headerIndex = lines.findIndex(l => l.trim().toLowerCase() === target)
  if (headerIndex === -1) return ''
  for (let i = headerIndex + 1; i < lines.length; i++) {
    const line = lines[i].trim()
    if (line.startsWith('###')) break
    if (line && line !== '_No response_') return line
  }
  return ''
}

// Returns all content lines between the matching ### heading and the next ### heading
function parseMultiLineField(body: string, label: string): string {
  const lines = body.split('\n')
  const target = `### ${label.toLowerCase()}`
  const headerIndex = lines.findIndex(l => l.trim().toLowerCase() === target)
  if (headerIndex === -1) return ''
  const collected: string[] = []
  for (let i = headerIndex + 1; i < lines.length; i++) {
    const trimmed = lines[i].trim()
    if (trimmed.startsWith('###')) break
    if (trimmed !== '_No response_') collected.push(trimmed)
  }
  // Strip leading/trailing empty entries
  while (collected.length && !collected[0]) collected.shift()
  while (collected.length && !collected[collected.length - 1]) collected.pop()
  return collected.join(' ')
}

function parseTags(body: string): string[] {
  const raw = parseField(body, 'Tags')
  if (!raw) return []
  return raw.split(',').map(t => t.trim()).filter(Boolean)
}

// The Sections field contains sub-### headings for each planned section.
// We extract the block between "### Sections" and "### Key Takeaways".
function parseSections(body: string): ParsedSection[] {
  const lines = body.split('\n')
  const sectionsIndex = lines.findIndex(l => l.trim().toLowerCase() === '### sections')
  if (sectionsIndex === -1) return []
  const takeawaysIndex = lines.findIndex(
    (l, i) => i > sectionsIndex && l.trim().toLowerCase() === '### key takeaways'
  )
  const endIndex = takeawaysIndex === -1 ? lines.length : takeawaysIndex

  const result: ParsedSection[] = []
  let i = sectionsIndex + 1
  while (i < endIndex) {
    const line = lines[i].trim()
    if (line.startsWith('### ')) {
      const title = line.slice(4).trim()
      let description = ''
      i++
      while (i < endIndex) {
        const descLine = lines[i].trim()
        if (descLine.startsWith('### ')) break
        if (descLine && descLine !== '_No response_') {
          description = descLine
          i++
          // Skip remaining lines in this sub-block
          while (i < endIndex && !lines[i].trim().startsWith('### ')) i++
          break
        }
        i++
      }
      if (title) result.push({ title, description })
    } else {
      i++
    }
  }
  return result
}

function parseTakeaways(body: string): string[] {
  const lines = body.split('\n')
  const headerIndex = lines.findIndex(l => l.trim().toLowerCase() === '### key takeaways')
  if (headerIndex === -1) return []
  const result: string[] = []
  for (let i = headerIndex + 1; i < lines.length; i++) {
    if (isTopLevelField(lines[i])) break
    const line = lines[i].trim()
    if (line.startsWith('- ') && line.length > 2) result.push(line.slice(2).trim())
  }
  return result.filter(Boolean)
}

onMounted(async () => {
  const params = new URLSearchParams(window.location.search)
  const issueParam = params.get('issue')

  if (!issueParam || !/^\d+$/.test(issueParam)) {
    state.value = 'error-invalid'
    return
  }

  const issueNumber = parseInt(issueParam, 10)

  try {
    const [issueRes, redirectRes] = await Promise.all([
      fetch(`https://api.github.com/repos/BANCS-Norway/home/issues/${issueNumber}`),
      fetch('/upcoming-redirects.json'),
    ])

    if (issueRes.status === 404 || !issueRes.ok) {
      state.value = 'error-notfound'
      return
    }

    const issue = await issueRes.json()
    let redirectMap: Record<string, string> = {}
    if (redirectRes.ok) {
      try {
        redirectMap = await redirectRes.json()
      } catch {
        // non-JSON response (e.g. dev server SPA fallback HTML) — treat as empty
      }
    }

    const labels: string[] = (issue.labels ?? []).map((l: { name: string }) => l.name)
    if (!labels.includes('upcoming-post')) {
      state.value = 'error-wrong-label'
      return
    }

    if (issue.state === 'closed') {
      const slug = redirectMap[String(issueNumber)]
      if (slug) {
        state.value = 'redirecting'
        window.location.href = slug
      } else {
        state.value = 'published'
      }
      return
    }

    const body = issue.body ?? ''
    post.value = {
      title: issue.title,
      series: parseField(body, 'Series (optional)'),
      estimated: parseField(body, 'Estimated publish'),
      tags: parseTags(body),
      summary: parseMultiLineField(body, 'Summary'),
      sections: parseSections(body),
      takeaways: parseTakeaways(body),
    }
    state.value = 'preview'
  } catch {
    state.value = 'error-notfound'
  }
})
</script>

<template>
  <div class="max-w-3xl mx-auto px-4 py-12 sm:py-16">

    <!-- Loading -->
    <p v-if="state === 'loading'" class="text-[var(--vp-c-text-2)] italic text-center py-16">
      Loading...
    </p>

    <!-- Redirecting -->
    <p v-else-if="state === 'redirecting'" class="text-[var(--vp-c-text-2)] italic text-center py-16">
      Taking you to the published post...
    </p>

    <!-- Error / fallback states -->
    <div
      v-else-if="state === 'published' || state === 'error-invalid' || state === 'error-notfound' || state === 'error-wrong-label'"
      class="text-center py-16"
    >
      <p class="text-[var(--vp-c-text-1)] text-lg mb-6">
        <template v-if="state === 'published'">
          This post has been published — head back to the blog to read it.
        </template>
        <template v-else>
          We couldn't find that post. The link may be invalid or the post may have been removed.
        </template>
      </p>
      <a
        href="/blog/"
        class="inline-block px-6 py-3 rounded-md font-semibold no-underline transition-all duration-250 bg-[var(--vp-c-brand)] !text-white hover:bg-[var(--vp-c-brand-dark)]"
      >
        Read the blog
      </a>
    </div>

    <!-- Preview -->
    <template v-else-if="state === 'preview' && post">

      <!-- Under construction hero -->
      <div class="flex flex-col items-center mb-10">
        <picture class="flex justify-center w-full max-h-[28vh]">
          <source
            srcset="/images/404_viking_bear.webp 1x, /images/404_viking_bear@2x.webp 2x"
            type="image/webp"
          />
          <img
            src="/images/404_viking_bear.png"
            srcset="/images/404_viking_bear.png 1x, /images/404_viking_bear@2x.png 2x"
            alt="A Viking and a bear sitting together by a campfire — still building this one"
            width="1024"
            height="1024"
            class="w-auto h-auto max-h-[28vh] mx-auto"
          />
        </picture>

        <span
          class="inline-block mt-4 px-3 py-1 rounded-full text-xs font-semibold tracking-wide uppercase bg-[var(--vp-c-brand-soft)] text-[var(--vp-c-brand-1)]"
        >
          Coming soon
        </span>
      </div>

      <!-- Post title -->
      <h1 class="!text-3xl sm:!text-4xl font-bold leading-tight mb-4 mt-0 text-[var(--vp-c-text-1)]">
        {{ post.title }}
      </h1>

      <!-- Meta row -->
      <div class="flex flex-wrap items-center gap-x-4 gap-y-2 mb-8 text-sm text-[var(--vp-c-text-2)]">
        <span v-if="post.series" class="font-medium text-[var(--vp-c-brand-1)]">
          {{ post.series }}
        </span>
        <span v-if="post.estimated">
          {{ post.estimated }}
        </span>
        <div v-if="post.tags.length > 0" class="flex flex-wrap gap-1">
          <span
            v-for="tag in post.tags"
            :key="tag"
            class="inline-block px-2 py-0.5 rounded text-xs font-medium bg-[var(--vp-c-brand-soft)] text-[var(--vp-c-brand-1)]"
          >{{ tag }}</span>
        </div>
      </div>

      <!-- Summary -->
      <p v-if="post.summary" class="text-lg leading-relaxed text-[var(--vp-c-text-1)] mb-10">
        {{ post.summary }}
      </p>

      <!-- Planned sections -->
      <div v-if="post.sections.length > 0" class="mb-10">
        <h2 class="!text-xl font-semibold mb-4 text-[var(--vp-c-text-1)] border-b border-[var(--vp-c-divider)] pb-2">
          Planned sections
        </h2>
        <ol class="list-none p-0 space-y-3">
          <li
            v-for="(sec, index) in post.sections"
            :key="sec.title"
            class="flex gap-3 p-4 rounded-lg bg-[var(--vp-c-bg-soft)]"
          >
            <span class="shrink-0 w-6 h-6 rounded-full bg-[var(--vp-c-brand-soft)] text-[var(--vp-c-brand-1)] text-xs font-bold flex items-center justify-center mt-0.5">
              {{ index + 1 }}
            </span>
            <div>
              <span class="font-semibold text-[var(--vp-c-text-1)]">{{ sec.title }}</span>
              <span v-if="sec.description" class="block text-sm text-[var(--vp-c-text-2)] mt-0.5">
                {{ sec.description }}
              </span>
            </div>
          </li>
        </ol>
      </div>

      <!-- Key takeaways -->
      <div v-if="post.takeaways.length > 0" class="mb-10">
        <h2 class="!text-xl font-semibold mb-4 text-[var(--vp-c-text-1)] border-b border-[var(--vp-c-divider)] pb-2">
          Key takeaways
        </h2>
        <ul class="space-y-2 p-0">
          <li
            v-for="item in post.takeaways"
            :key="item"
            class="flex gap-2 text-[var(--vp-c-text-1)] list-none"
          >
            <span class="shrink-0 text-[var(--vp-c-brand-1)] font-bold">—</span>
            <span>{{ item }}</span>
          </li>
        </ul>
      </div>

      <!-- CTA -->
      <div class="mt-12 pt-8 border-t border-[var(--vp-c-divider)] text-center">
        <p class="text-[var(--vp-c-text-2)] mb-4">
          Want to know when this publishes? Follow us on
          <a href="https://github.com/BANCS-Norway" class="text-[var(--vp-c-brand-1)] no-underline hover:underline" rel="noopener">GitHub</a>
          or subscribe to the
          <a href="/blog/" class="text-[var(--vp-c-brand-1)] no-underline hover:underline">RSS feed</a>.
        </p>
        <a
          href="/blog/"
          class="inline-block px-6 py-3 rounded-md font-semibold no-underline transition-all duration-250 bg-[var(--vp-c-bg-soft)] text-[var(--vp-c-text-1)] border border-[var(--vp-c-divider)] hover:border-[var(--vp-c-brand)] hover:text-[var(--vp-c-brand)]"
        >
          Back to the blog
        </a>
      </div>

    </template>

  </div>
</template>
